version: "3"
services:
  myactivemq:
    image: rmohr/activemq:5.15.9
    container_name: myactivemq
    restart: always
    ports:
      - 8161:8161
      - 61616:61616
    volumes:
       - activemqdata:/opt/activemq/data

volumes:
    activemqdata:
